#!/usr/bin/env bash
# Script that copies a file from client to the the server

# Check if all the arguments are given
if [ $# -lt 4 ]; then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME [PATH_TO_SSH_KEY]"
  exit 1
fi

# Assigning parameters to variables
file_path="$1"
server_ip="$2"
username="$3"
ssh_key="$4"

# SCP command to transfer the file to the server
scp_command="scp -o StrictHostKeyChecking=no -i \"$ssh_key\" \"$file_path\" \"$username@$server_ip:~/\""

# Execute the SCP command
eval "$scp_command"

