#!/usr/bin/env bash
# This script installs nginx and configures it to listen
#+	on port 80 and return "Hello World" when querried
#+	on its root

# update packages lists
apt-get update

# Install Nginx
apt-get install -y nginx

# Configure Nginx
cat > /etc/nginx/sites-available/default <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    location / {
        try_files \$uri \$uri/ =404;
    }

    location = / {
        try_files /index.html =404;
    }
}
EOF

cat > /var/www/html/index.html <<EOF
<!DOCTYPE html>
<html>
  <head>
    <title>Web-01 ROOT</title>
  </head>
  <body>
    <h1>Holberton School</h1>
    <h3>Project being developed by Julius Mwangi, the tech genius</h3>
    <h3>Thanks to our mentors, fellow peers, and everyone associated with the ALX program</h3>
    <h3>Really appreciate the good work done by you -> ALX team</h3>
  </body>
</html>
EOF

# Restart Nginx
service nginx restart
