#!/usr/bin/env bash
# Redirect to another page

apt-get update
apt-get install -y nginx
cat > /etc/nginx/sites-available/default <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    location / {
        try_files \$uri \$uri/ =404;
    }

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    location = / {
        return 200 "Hello World!\n";
    }
    error_page 404 /404.html;
}
EOF

# Restart Nginx
service nginx restart

