#!/usr/bin/env bash
# Configure Nginx to redirect the page
sed -i '/server_name _;/a \
\\n\tlocation /redirect_me {\
\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\
\n\t}' /etc/nginx/sites-available/default

# Restart Nginx
service nginx restart

