#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom
#+	header

configure_nginx() {
  ssh -i ~/.ssh/school ubuntu@"$1" << EOF
    sudo sed -i 's/# server_tokens off;/server_tokens off;/' /etc/nginx/nginx.conf
    sudo sed -i '/http {/a\\\tadd_header X-Served-By \$hostname;' /etc/nginx/nginx.conf
    sudo service nginx restart
EOF
}

configure_nginx "34.207.155.64"
configure_nginx "54.208.222.77"

