#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom
#+	header

git clone --quiet https://github.com/Juliusmwash/alx-system_engineering-devops.git

mv alx-system_engineering-devops/0x0C-web_server/4-not_found_page_404 .
rm -rf alx-system_engineering-devops
sudo ./4-not_found_page_404

sudo sed -i "/http {/a\\\tadd_header X-Served-By \$hostname;" /etc/nginx/nginx.conf
sudo service nginx restart

