#!/usr/bin/env bash
# Bash script that displays listening ports

#echo "Active Internet connections (only servers)"
#echo "Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name"
#netstat -lntu | awk '$6 == "LISTEN" {print $0}' | awk '{printf "%-4s %-7s %-7s %-24s %-22s %-13s ", $1, $2, $3, $4, $5, $6; system("lsof -i :"substr($4, index($4, \":\")+1)" | awk '{if (NR!=1) print $2\"/\"$1}'")}'
#echo ""
#echo "Active UNIX domain sockets (only servers)"
#echo "Proto RefCnt Flags       Type       State         I-Node   PID/Program name    Path"
#netstat -lnux | awk '$6 == "LISTEN" {print $0}' | awk '{printf "%-4s %-7s %-7s %-10s %-12s %-9s ", $1, $2, $3, $4, $5, $6; system("lsof -U "substr($8, 2)" | awk '{if (NR!=1) print $2\"/\"$1}'")}'

nestat -l --program
