#!/usr/bin/env bash
# Does some operations

# Create PID file
echo $$ > /var/run/myscript.pid

# Signal handler functions
term_handler() {
    echo "I hate the kill command"
    rm /var/run/myscript.pid
    exit 1
}

int_handler() {
    echo "Y U no love me?!"
}

quit_handler() {
    rm /var/run/myscript.pid
    exit 0
}

# Set signal handlers
trap 'term_handler' SIGTERM
trap 'int_handler' SIGINT
trap 'quit_handler' SIGQUIT

# Display message indefinitely
while true
do
    echo "To infinity and beyond"
    sleep 2
done

