#!/usr/bin/env bash
# prints "To infinity and beyond" indefinitely
#+ With a sleep 2 in between each iteration
#+ "I am invincible!!!" when receiving a SIGTERM signal

trap 'echo "I am invincible!!!"; pkill -TERM -f "7-highlander"' SIGTERM

while true; do
  echo "To infinity and beyond"
  sleep 2
done

