#!/usr/bin/env bash
# prints "To infinity and beyond" indefinitely
#+ With a sleep 2 in between each iteration
#+ "I am invincible!!!" when receiving a SIGTERM signal

# Define the signal handler for SIGTERM
function sigterm_handler {
  echo "I am invincible!!!"
  exit 0
}

# Register the signal handler for SIGTERM
trap sigterm_handler SIGTERM

# Loop indefinitely, displaying "To infinity and beyond"
while true; do
  echo "To infinity and beyond"
  sleep 2
done

