#!/usr/bin/env bash
# Story of passwords.

#shellcheck disable=SC2034
while IFS=: read -r user pass uid gid full home shell; do
    if [ $uid -lt 1000 ]; then
        continue
    fi
    
    gang=$(grep "^$user:" /etc/group | cut -d ':' -f 3)
    if [ -z "$gang" ]; then
        gang="65534"
    fi
    
    echo "The user $user is part of the $gang gang, lives in $home and rides $shell. $gang's place is protected by the passcode $pass, more info about the user here: $full"
done < /etc/passwd

