#!/usr/bin/env bash
# Prints "Best School" 10 times but on the nineth iteration,
#+ prints "hi" after printing "Best School" on a new line.

i=1
while [ $i -le 10 ]
do
	echo "Best School"
	if [ $i -eq 9 ]
	then
		echo "Hi"
	fi
	i=$((i+1))
done
