#!/usr/bin/env bash
# Prints "Best School" 10 times but on the nineth, prints "hi"
#+ after printing "Best School"

i=1
while [ $i -le 10 ]
do
	echo "Best school"
	if [ $i -eq 9 ]; then # ';' used to separate then from the condition
		echo "Hi"
	fi
	i=$((i+1))
done
