#!/usr/bin/env bash
# Prints numbers from 1 to 20.
# Prints "bad luck from China immediately after printing the number 4.
# Prints "bad luck from Japan" immediately after printing the number 9.
# Prints "bad luck from Italy" immediately after printing the number 17.

i=1
while [ $i -le 20 ]
do
	echo "Best School"
	if [ $i -eq 4 ]
	then
		echo "bad luck from China"
	elif [ $i -eq 9 ]
	then
		echo "bad luck from Japan"
	elif [ $i -eq 17 ]
	then
		echo "bad luck from Italy"
	fi
	i=$((i+1))
done
