#!/usr/bin/env bash
# Prints numbers from 1 to 20.
# Prints "bad luck from China immediately after printing the number 4.
# Prints "bad luck from Japan" immediately after printing the number 9.
# Prints "bad luck from Italy" immediately after printing the number 17.

i=1
while [ $i -le 20 ]
do
	case $i in
		4)
			echo -e "$i\nbad luck from China"
			;;
		9)
			echo -e "$i\nbad luck from Japan"
			;;
		17)
			echo -e "$i\nbad luck from Italy"
			;;
		*)
			echo "$i"
	esac
	i=$((i+1))
done
