#!/usr/bin/env bash
# Prints the content of the current directory in a list format
#+ where only the part of the name after the first dash is displayed (refer to the example)

for word in *
do
	echo "${word#*-}"
done
