#!/usr/bin/env bash
# Checks for the existence of the file 'school'
#+ If it exists, proceeds to check whether it's empty.
#+ Also checks if it is a regular file.

if [ -e "school" ]; then
    echo "school file exists"
    if [ -s "school" ]; then
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi
    if [ -f "school" ]; then
        echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi
