#!/usr/bin/env bash
# Bash script that configures an Ubuntu server

cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1 localhost/127.0.0.2 localhost/' ~/hosts.new
sed -i '/facebook.com/ s/.*/8.8.8.8 facebook.com/' ~/hosts.new
cp -f ~/hosts.new /etc/hosts

